language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.6.5-linux64.tar.xz
  - tar xf arduino-1.6.5-linux64.tar.xz
  - sudo mv arduino-1.6.5 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
  - wget https://github.com/PaulStoffregen/Time/archive/v1.5.tar.gz
  - tar xf v1.5.tar.gz
  - sudo mv Time-1.5 /usr/local/share/arduino/libraries/Time
  - sudo ls /usr/local/share/arduino/libraries
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/MicroGNC
  - arduino --install-library "Time"
script:
  - arduino --verify --board arduino:avr:uno $PWD/examples/CourseComputer/CourseComputer.ino
notifications:
  email:
    on_success: change
    on_failure: change